### ISSUE TITLE
Sorting comparison: Allow milliseconds time jitter instead of the number of samples (delta_tp) 

### ISSUE THREAD

**Issue by jamesjun** [SpikeInterface/spiketoolkit#128]
Sorting comparison class should allow milliseconds input instead of allowing the number of samples by passing delta_tp. Currently, the sorting comparison doesn't take different sampling rate into account, penalizing higher sampling rate recordings.

**Comment by alejoe91** [comment]
@jamesjun that's a good point.
In order to do that we have to add a `self.sampling_frequency()` variable to all extractors. Right noe SortingExtractor don't have sample rate information, but I think it's a great addition.

@colehurwitz @samuelgarcia what do you guys think?

**Comment by colehurwitz** [comment]
I don't think we should add sampling_frequency to the sorting extractor. We already kinda talked about this and we agreed that it should be a part of the recording extractor only (which it is) since the sorting extractor doesn't necessarily know about the recording.

I would recommend adding a sampling frequency argument to the function instead.

**Comment by alejoe91** [comment]
I think the spike sorter knows the sampling frequency. It's a required parameter to all sorters and if we don't have it in the sorting extractors we will always have to tag along the recording extractor.
I think it doesn't harm to add it as a property

**Comment by colehurwitz** [comment]
Hmm.. I am not sure the sorting extractor should have it as a property. Right now we only ever deal with unit properties, so there really isn't a concept of global properties. 

I think putting sampling frequency as an argument makes more sense because if you are running the sorter (and it returns the sorting extractor) than you definitely have access to the recording extractor already. And for the times that you are using a sorting extractor without using a sorter, you would have to manually set that property before using the comparison which is clunky.

**Comment by alejoe91** [comment]
I don't agree. I think it's muuuuch easier to have a get sampling frequency internally.

Think you want to load a sorting output later and compute something: you don't want to track back and load the original recording...

**Comment by colehurwitz** [comment]
If sampling frequncies are not stored in the sorting files then they shouldn’t be stored in the sorting extractors. Do any formats have access to this information? 

If no formats have this information, then I am not sure what adding this to the sorting extractor gains you because you need to know the sampling frequency from the recording anyways.

**Comment by colehurwitz** [comment]
It’s not like we ever save a sorting extractor object so the information about sampling frequency would have to be known by the user each time and added

**Comment by samuelgarcia** [comment]
@jamesjun  : I agree that this params should be in ms.
Indeed a default params is never changed because we all forgot it so having it in ms is safer.

As neo member, I put lot of important on unit :)

sample are unitsless without the sampling rate!
so yes I think we need the sampling rate somewhere and internally preferentially.

For ISI violation it will be the same we need

@colehurwitz : does it represent lot of work in spikeextractor ?
We could have an optional method get_sampling_rate() if if wa have it then the sampling rate is not need in sorting comparison but if not then the user must manually propagate it into SorintgCOmaprison.
No ?

**Comment by colehurwitz** [comment]
I think it would be better to have the user manually propagate it. Recording extractors have access to the sampling rate, but I don't think any sorting file format does. So the only way for sorting extractors to get that information is manually (which makes it equivalent to passing it into sorting comparison).

I don't necessarily see the benefit of letting sorting extractors have it... but if that is what you guys agree on, I can implement it pretty easily.

**Comment by alejoe91** [comment]
I think all sorting extractors would have that info :) at least klusta kilosort phy etc..

**Comment by colehurwitz** [comment]
Hmm.. Well, maybe we can include it as an optional thing then... what do you think the best way to include it would be?

**Comment by alejoe91** [comment]
I'll try to do this today :)

**Comment by alejoe91** [comment]
https://github.com/SpikeInterface/spiketoolkit/pull/177

**Comment by alejoe91** [comment]
@jamesjun merged now. https://github.com/SpikeInterface/spiketoolkit/pull/177

This requires sorting extractors to have a `self._sampling_frequency` field, that is returned with the `get_sampling_frequency()` method

**Comment by samuelgarcia** [comment]
Note not all extractor need the frequency, at least the GT one is necessary.

**Comment by alejoe91** [comment]
why not @samuelgarcia ? Since we use delta_time, the sampling frequency information should be 1) present in both sorting extractor, 2) it should be the same in both extractors.

**Comment by colehurwitz** [comment]
I think the assumption, when you are comparing to ground truth, is that you sorted the same dataset as the ground truth, therefore, the sampling frequency can be assumed to be the same.

**Comment by alejoe91** [comment]
I agree, but it's good to check. The user could compare one GT dataset with another sorter result with a different fs without knowing. I see no harm in checking for this

**Comment by colehurwitz** [comment]
Ok, but it shouldn't fail if the non-ground truth sorting extractor has no fs.

**Comment by alejoe91** [comment]
and for the compare_two_sorters?

**Comment by colehurwitz** [comment]
Not sure exactly... I feel as though it should work about the same as the ground truth case, but maybe @samuelgarcia has a better idea about that.

**Comment by alejoe91** [comment]
I think that then we should check both sorting extractors. Even for the GT ones one can easily load the sampling frequency with the set_sampling_frequency function

**Comment by colehurwitz** [comment]
I don't mind either solution. Both seem fine.

**Comment by samuelgarcia** [comment]
@alejoe91 : in the context of groundTruthSortingComparison the rule of sampling rate could be "at leat one of the two otherwise explicitly given" and for SortingComparison "the two are the same otherwise explicitly given.

Since some sorter don't have internally the fs but the GT (like mearec) have the fs most of the time, it would be more flexible for the end user.

No ?

**Comment by alejoe91** [comment]
Ok that sounds right! I'll make a PR tomorrow :)
