### ISSUE TITLE
Testing each sorter requires installing each one

### ISSUE THREAD

**Issue by colehurwitz31** [SpikeInterface/spiketoolkit#43]
@samuelgarcia @alejoe91 

So the reason the build isn't passing now is that the test you included for trideclous (while nice to have) requires that travis install trideclous. I could make travis install that package before testing, but then we might run into issues testing multiple sorters which different dependencies.

Do you have an idea about how to test each sorter with travis?

**Comment by samuelgarcia** [comment]
For now the best is to left Travis in red.
I started working with class since one hour. I will make a proposal today via a PR.

The new class will make possible to make test or not depending SorterClass.installed or not.

What do you think ?

Matlab sorter will never be tested in travis for instance.

About tridesclous, this run test on circle-ci. It is possible to install via a simple pip isntall and also all thedependency except pyopencl which is a weak dependency).

**Comment by colehurwitz31** [comment]
Yes, that does sound like a good idea. I am looking forward to your PR.

**Comment by alejoe91** [comment]
tests are passing :) closing this one
