### ISSUE TITLE
Flat dictionaries for HS and tridesclous

### ISSUE THREAD

**Issue by martinosorb** [SpikeInterface/spiketoolkit#68]
As mentioned in the call, we should "expose" the parameters to the user. An option that I would suggest is to use a hybrid approach. Parameters that we consider important (i.e. the ones that the user almost always will want to change) are in `self.params`. The other parameters are in one or more dictionaries which are themselves in `self.params`:

```python
self._default_params = {
    'important_par1': 0.0,
    'important_par1': True,
    'other_pars': { 'par1': 0.0, 'par2': 0.0 }
}
```
In this way, the user can use `set_params` directly for the main parameters, and, if advanced parameters need to be changed, can go through the more complex procedure of building a new dictionary and passing it to `set_params`.

Just an idea, what do you think?

**Comment by alejoe91** [comment]
@martinosorb 

I think this could be a good idea. 'other_pars' would also be a flat dictionary right?

**Comment by martinosorb** [comment]
Potentially could be nested, that would make it simpler to then pass those arguments. But I can make it flat if you prefer.

@mhhennig @colehurwitz31 can we agree on what parameters should be considered "important" and "often tuned by the user" in HS? Definitely `alpha, bandwidth, n_jobs` on the clustering side (and I suggest setting a default bin_seeding=True perhaps?) and `threshold` for the detection. Cutout start, end should be made fixed once HS is turned into using milliseconds as units.
What about probe params?

**Comment by mhhennig** [comment]
For detection, I agree `threshold` matters most. There is also:

`maa`: minimum spike area (cumulative), to exclude 1 frame baseline deviations
`maxsl`: maximum width of negative deflection
`minsl`: interval to compute `maa` over
`ahpthr`: value the repolarisation has to exceed to be counted as spike
`inner_radius`: spatial radius used to compute centre of mass
`neighbor_radius`: maximum spatial spread of signals, for excluding duplicates
`cutout_start`: frames before peak to include in cutouts
`cutout_end`: frames after peak to include in cutouts

Spatial parameters should be in um (need to adjust the biocam probe here), temporal parameters best in ms, to be converted to frames using the sampling rate internally.

Clustering:
`pca_ncomponents`: default 2
`alpha`, `bandwidth`: perhaps default to about 8, 8um
`cluster_subset`: important for performance, can be set to 200,000 or so, so that only a subset of events will be used to form clusters

**Comment by alejoe91** [comment]
@samuelgarcia any update on this?

**Comment by samuelgarcia** [comment]
I will do this very soon.
Once the PR on  performance will be done.

**Comment by samuelgarcia** [comment]
About HS, you should add the possibility to apply a filter or not in  the flat dict.
In actual implementaion there is not filtering step.
For some dataset it will give silly results.

**Comment by samuelgarcia** [comment]
I think we must do this before the release.

**Comment by martinosorb** [comment]
For herdingspikes, we now have the main parameters available on the first level of the dict, and less important ones in nested dicts inside the main one. This is what we had agreed on at some point. Is it ok as it is, or should we discuss further? I had a chat with Cole and Matthias and they're not convinced.

**Comment by alejoe91** [comment]
I think it would be better to add the `other_params` internally like it's done in tridesclous.

I agree with @samuelgarcia that `filter` should be an option, and the spiketoolkit.preprocessing.bandpass filter can be used

**Comment by alejoe91** [comment]
https://github.com/SpikeInterface/spiketoolkit/pull/122
